title: Frissiano Honwana
logo: /images/FHonwana.png
description: Biostatistician 🧩 | Division of Epidemiology & Biostatistics | School of Public Health University of Cape Town Interests: Football ⚽️ & Combat Sports🥋🥊
#show_downloads: true
theme: jekyll-theme-minimal

