# Basic Site Settings
title: Frissiano Honwana | Biostatistician
logo: /images/FHonwana.png
description: Biostatistician specialising in prediction modelling
url: "https://frissianohonwana.github.io"

#show_downloads: true
theme: ~
remote_theme: ~

plugins: []
