---
title: "Frissiano E. Honwana"
about:
  template: broadside
  links:
    - text: "{{< iconify ic:baseline-email size=2xl >}}"
      href: mailto:frissiano.honwana@uct.ac.za
    - text: "{{< iconify mdi:linkedin size=2xl >}}"
      href: https://za.linkedin.com/in/frissiano-honwana-phd-b127b2b6
    - text: "{{< iconify academicons:google-scholar size=2xl >}}"
      href: https://scholar.google.com/citations?user=Ol-nisMAAAAJ&hl=en
---

I am Frissiano Honwana, a biostatistician in the Division of Epidemiology and Biostatistics in the School of Public Health at the University of Cape Town (UCT).

My research interests are in prediction modelling using biomarkers. It focuses on improving healthcare outcomes by integrating advanced statistical techniques to improve disease prediction and patient
care. Through my research, I seek to refine diagnostic accuracy and optimize treatment strategies, thereby contributing to the advancement of precision medicine. 

Additionally, I serve as a lecturer and convene courses for UCT’s Master of Public Health (MPH) program, MSc in Epidemiology and Biostatistics, and for fourth-year MBChB students.

I earned an MSc in statistics from the University of KwaZulu-Natal and a PhD degree in public health (Biostatistics) from UCT. 
